name: CI - Calculator

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-infra-deploy:
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v4

      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      
      - name: Install dependencies
        run: npm install

      
      - name: Run tests
        run: npm test

      
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1

      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      
      - name: Terraform Init
        working-directory: infra
        run: terraform init

      
      - name: Terraform Validate
        working-directory: infra
        run: terraform validate

     
      - name: Terraform Apply
        working-directory: infra
        run: terraform apply -auto-approve -refresh=true

      
      - name: Build Docker image
        run: docker build -t calculator-app .

      
      - name: Run Docker container
        run: docker run -d -p 8080:80 calculator-app

      
      - name: Wait for container
        run: sleep 5

      
      - name: Test container
        run: curl http://localhost:8080

      
      - name: Deploy to S3
        run: aws s3 sync src/ s3://disciplina-devops-caroline-b2/ --delete